#!/bin/bash

set -o pipefail

typeset -a filter=()
if [ $# -ge 2 ] && [ "${@:(-2):1}" = -- ]; then
    filter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

getAllPodHosts()
{
    kubectl get pods "$@" -o go-template --template '{{range .items}}{{if not .status.reason}}{{.metadata.name}}{{"\t"}}{{.spec.nodeName}}{{"\n"}}{{end}}{{end}}'
}

eval 'getAllPodHosts "$@"' "${filter:+|}" '"${filter[@]}"' | awk -F '\t' '
{
    c[$2] += 1
    if (e[$2])
	e[$2] = e[$2] "\n\t" $1
    else
	e[$2] = "\t" $1
}
END {
    for (i in e) {
	print i " (" c[i] "):"
	print e[i]
    }
}
'
