#!/bin/bash

set -o pipefail

typeset -a filter=()
if [ $# -ge 2 -a "${@:(-2):1}" = -- ]; then
    typeset -a filter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

getAllPodImages()
{
    kubectl get "$@" -o go-template --template '{{range .items}}{{.metadata.name}}{{"\t"}}{{range .status.containerStatuses}}    {{.image}} {{.containerID}}{{"\t"}}{{end}}{{"\n"}}{{end}}' pods
}

eval 'getAllPodImages "$@"' "${filter:+|}" '"${filter[@]}"' | sed -e 's#\t#\n#g'
