#!/bin/bash

set -o pipefail

typeset -a filter=()
if [ $# -ge 2 ] && [ "${@:(-2):1}" = -- ]; then
    filter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

: ${KUBECTL_IGNORE_CONTAINERNAMES=kubernetes-vault-renew}
typeset -a containerFilter=()
if [ "$KUBECTL_IGNORE_CONTAINERNAMES" ]; then
    ignoredContainerBranches="${KUBECTL_IGNORE_CONTAINERNAMES// /\\|}"
    containerFilter=(sed -e "s# \\(${ignoredContainerBranches}\\): [^ ]\+\\( \\|\$\\)#\\2#")
fi

getAllPodContainerStartTimes()
{
    local -r SELECTOR='{{.metadata.name}}{{range .status.containerStatuses}} {{.name}}: {{if .state.running}}{{.state.running.startedAt}}{{else}}{{ range $key, $value := .state }}{{$key}}{{end}}{{end}}{{end}}{{if .status.reason}} (Status:{{.status.reason}}){{end}}{{"\n"}}'
    kubectl get pods "$@" -o go-template --template "{{if .items}}{{range .items}}${SELECTOR}{{end}}{{else}}${SELECTOR}{{end}}"
}

eval 'getAllPodContainerStartTimes "$@"' "${filter:+|}" '"${filter[@]}"' "${containerFilter:+|}" '"${containerFilter[@]}"'
