#!/bin/bash

exec kubectl get "$@" -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{range .status.containerStatuses}}    {{.image}} {{.containerID}}{{"\n"}}{{end}}{{"\n"}}{{end}}' pods
