#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Query the container IDs for PODs [matching EXPR] [of container CONTAINER-NAME].
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[KUBECTL-ARGS] [-- EXPR] [-c CONTAINER-NAME] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac


exec kubectl-podinfo '{{.containerID}}' "$@"
