#!/bin/bash

set -o pipefail

typeset -a filter=()
if [ $# -ge 2 ] && [ "${@:(-2):1}" = -- ]; then
    filter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

getAllCompletedPods()
{
    local -r SELECTOR='{{if eq .status.phase "Succeeded" }}{{.metadata.name}}{{"\t"}}{{.status.startTime}}{{"\n"}}{{end}}'
    kubectl get pods "$@" -o go-template --template "{{if .items}}{{range .items}}${SELECTOR}{{end}}{{else}}${SELECTOR}{{end}}"
}

eval 'getAllCompletedPods "$@"' "${filter:+|}" '"${filter[@]}"' | reldate --date-pattern '\b(?<year>\d\d\d\d)-(?<month>\d\d)-(?<day>\d\d)T(?<hours>\d\d):(?<minutes>\d\d):(?<seconds>\d\d)(?<timezone>Z)\b' --prefer-past
