#!/bin/bash

set -o pipefail

queryItem=${1:?}; shift
typeset -a finalFilter=(sed -e 's#\t#\n#g')

filterContainer=
if [ $# -ge 2 ] && [ "${@:(-2):1}" = '-c' ]; then
    filterContainer=${!#}
    set -- "${@:1:$(($#-2))}"

    # Omit PODs that don't have any matching queryItems.
    finalFilter=(sed -e '/^[^\t]\+\t$/d')
fi

typeset -a podFilter=()
if [ $# -ge 2 ] && [ "${@:(-2):1}" = -- ]; then
    podFilter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

getAllPodImages()
{
    if [ "$filterContainer" ]; then
	local template='{{range .items}}{{if not .status.reason}}{{.metadata.name}}{{"\t"}}{{range .status.containerStatuses}}{{if eq .name "'"$filterContainer"'"}}'"$queryItem"'{{end}}{{end}}{{"\n"}}{{end}}{{end}}'
    else
	local template='{{range .items}}{{if not .status.reason}}{{.metadata.name}}{{"\t"}}{{range .status.containerStatuses}}    {{.name}} '"$queryItem"'{{"\t"}}{{end}}{{"\n"}}{{end}}{{end}}'
    fi

    kubectl get pods "$@" -o go-template --template "$template"
}

eval 'getAllPodImages "$@"' "${podFilter:+|}" '"${podFilter[@]}"' "${finalFilter:+|}" '"${finalFilter[@]}"'
