#!/bin/bash
shopt -qs extglob

printUsage()
{
    cat <<HELPTEXT
Edit a resource's JSON definition with jq.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '-e JQ-FILTER [KUBECTL-OPTIONS ...] RESOURCE/NAME [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

typeset -a jqArgs=()
typeset -a kubectlGetArgs=()
typeset -a kubectlReplaceArgs=()
typeset -a kubectlOutputFormat=(-o json)
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	-e)			jqArgs+=("$2"); shift; shift;;
	-R)			kubectlReplaceArgs+=("$1"); shift;;
	--@(allow-missing-template-keys|cascade|force|grace-period|recursive|save-config|timeout)=*)	kubectlReplaceArgs+=("$1"); shift;;
	--@(allow-missing-template-keys|cascade|force|grace-period|recursive|save-config|timeout))	kubectlReplaceArgs+=("$1" "$2"); shift; shift;;
	--)		kubectlGetArgs+=("$1"); shift; break;;
	*)		kubectlGetArgs+=("$1"); shift;;
    esac
done
if [ ${#kubectlGetArgs[@]} -eq 0 -a $# -eq 0 ]; then
    printUsage "$0" >&2
    exit 2
elif [ ${#jqArgs[@]} -eq 0 ]; then
    echo >&2 'ERROR: No jq arguments.'
    printUsage "$0" >&2
    exit 2
fi


ORIGINAL=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX.in" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$${RANDOM}.in")
REPLACEMENT=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX.out" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$${RANDOM}.out")
cleanup()
{
    rm -f "$ORIGINAL" "$REPLACEMENT" 2>/dev/null
}
[ "$DEBUG" ] || trap 'cleanup' EXIT


kubectl get "${kubectlGetArgs[@]}" "${kubectlOutputFormat[@]}" "$@" > "$ORIGINAL" || exit $?
jq "${jqArgs[@]}" "$ORIGINAL" > "$REPLACEMENT" || exit $?
kubectl replace "${kubectlReplaceArgs[@]}" -f "$REPLACEMENT"
