#!/bin/bash

set -o pipefail

typeset -a filter=()
if [ $# -ge 2 ] && [ "${@:(-2):1}" = -- ]; then
    filter=(grep -e "^[^ ]*${!#}")
    set -- "${@:1:$(($#-2))}"
fi

getAllPodNames()
{
    kubectl get "$@" -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' pods
}

eval 'getAllPodNames "$@"' "${filter:+|}" '"${filter[@]}"'
