#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Delete and re-create passed resource.
Usage: "$(basename "$1")" [...] FILENAME [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

lastArg=${!#}
if [ $# -eq 0 -o ! -e "$lastArg" ]; then
    echo >&2 "ERROR: Must pass FILENAME"
    exit 2
fi

kubectl delete "${@:1:$(($#-1))}" -f "$lastArg" && kubectl create "${@:1:$(($#-1))}" -f "$lastArg"
